2025-10-21 19:04:41,835 - users_repository - ERROR - create_user:78 - {"user_id": "ce733f36-23f7-4c9a-a7dc-e20795fa37ec", "email": "docker-test@example.com", "error": "(psycopg2.errors.CheckViolation) new row for relation \"users\" violates check constraint \"users_role_check\"\nDETAIL:  Failing row contains (ce733f36-23f7-4c9a-a7dc-e20795fa37ec, docker-test@example.com, $2b$12$wEF5PytbDZhMduZ82CBzo.bh4DwXQaRni26g.eqQcFdRW57duU04m, CUSTOMER, {\"firstName\":\"Docker\",\"lastName\":\"Test\",\"phone\":\"+1234567890\",\"a..., 2025-10-21 19:04:41.83239+00, 2025-10-21 19:04:41.832395+00).\n\n[SQL: \n                INSERT INTO users (id, email, password, role, profile, created_at, updated_at)\n                VALUES (%(id)s, %(email)s, %(password)s, %(role)s, %(profile)s, %(created_at)s, %(updated_at)s)\n            ]\n[parameters: {'id': 'ce733f36-23f7-4c9a-a7dc-e20795fa37ec', 'email': 'docker-test@example.com', 'password': '$2b$12$wEF5PytbDZhMduZ82CBzo.bh4DwXQaRni26g.eqQcFdRW57duU04m', 'role': 'CUSTOMER', 'profile': '{\"firstName\":\"Docker\",\"lastName\":\"Test\",\"phone\":\"+1234567890\",\"address\":\"123 Docker St\"}', 'created_at': datetime.datetime(2025, 10, 21, 19, 4, 41, 832390, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2025, 10, 21, 19, 4, 41, 832395, tzinfo=datetime.timezone.utc)}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)", "event": "User creation failed - integrity error", "logger": "users_repository", "level": "error", "timestamp": "2025-10-21T19:04:41.835046Z"}
2025-10-21 19:04:54,881 - users_repository - ERROR - create_user:78 - {"user_id": "86be0bba-28fa-4368-ad0f-b787dd1095fa", "email": "docker-new@example.com", "error": "(psycopg2.errors.CheckViolation) new row for relation \"users\" violates check constraint \"users_role_check\"\nDETAIL:  Failing row contains (86be0bba-28fa-4368-ad0f-b787dd1095fa, docker-new@example.com, $2b$12$9aEc/rbiK4PM9oqkXb10hOkdIQbU/29Z68/z7Z56ez5xR.CgXWY.C, CUSTOMER, {\"firstName\":\"Docker\",\"lastName\":\"New\",\"phone\":\"+1234567890\",\"ad..., 2025-10-21 19:04:54.879061+00, 2025-10-21 19:04:54.879067+00).\n\n[SQL: \n                INSERT INTO users (id, email, password, role, profile, created_at, updated_at)\n                VALUES (%(id)s, %(email)s, %(password)s, %(role)s, %(profile)s, %(created_at)s, %(updated_at)s)\n            ]\n[parameters: {'id': '86be0bba-28fa-4368-ad0f-b787dd1095fa', 'email': 'docker-new@example.com', 'password': '$2b$12$9aEc/rbiK4PM9oqkXb10hOkdIQbU/29Z68/z7Z56ez5xR.CgXWY.C', 'role': 'CUSTOMER', 'profile': '{\"firstName\":\"Docker\",\"lastName\":\"New\",\"phone\":\"+1234567890\",\"address\":\"123 Docker St\"}', 'created_at': datetime.datetime(2025, 10, 21, 19, 4, 54, 879061, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2025, 10, 21, 19, 4, 54, 879067, tzinfo=datetime.timezone.utc)}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)", "event": "User creation failed - integrity error", "logger": "users_repository", "level": "error", "timestamp": "2025-10-21T19:04:54.881105Z"}
